name: Blog-REST-API-Node CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests and update check status
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          npm run test
          if [ $? -eq 0 ]; then
            echo "Tests passed"
            echo "::set-output name=tests_passed::true"
          else
            echo "Tests failed"
            echo "::set-output name=tests_passed::false"
          fi

      - name: Check test status and update branch protection
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testsPassed = ${{ steps.run tests and update check status.outputs.tests_passed }};
            const context = github.context;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            const status = testsPassed ? 'success' : 'failure';
            const sha = context.sha;
            const repo = context.repo;

            await octokit.repos.createCommitStatus({
              ...repo,
              sha: sha,
              state: status,
              context: 'CI/Test',
            });

            if (!testsPassed) {
              console.log("Tests failed. Branch protection status will not be updated.");
              return;
            }

            await octokit.repos.updateBranchProtection({
              ...repo,
              branch: 'develop',
              enforce_admins: true,
              required_status_checks: {
                strict: true,
                contexts: ['CI/Test'],
              },
            });
